version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.yml
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.yml
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.yml
      timeout: 300
      runas: root
# version: 0.0
# os: linux
# files:
#   - source: /index.html
#     destination: /var/www/html
# permissions:
#    - object: /var/www/html
#      pattern: "**"
#      owner: nginx 
#      group: nginx
#      mode: 755
#      type:
#        - file
#   hooks:     
#   AfterInstall:
#     - location: scripts/install_dependencies
#       timeout: 300
#       runas: root
#   ApplicationStart:
#     - location: scripts/start_server
#       timeout: 300
#       runas: root
#   ApplicationStop:
#     - location: scripts/stop_server
#       timeout: 300
#       runas: root