version: 0.0
os: linux
files:
  - source: /
    destination: /usr/share/nginx/html

permissions:
   - object: /usr/share/nginx/html
     pattern: "**"
     owner: nginx 
     group: nginx
     mode: 755
     type:
       - file

  # hooks:     
  # AfterInstall:
  #   - location: scripts/install_dependencies
  #     timeout: 300
  #     runas: root
  #   - location: scripts/start_server
  #     timeout: 300
  #     runas: root
  # ApplicationStop:
  #   - location: scripts/stop_server
  #     timeout: 300
  #     runas: root